In [2]:
import numpy as np

In [3]:
marks = np.array([
    [85, 78, 92, 88, 76],
    [72, 81, 69, 75, 80],
    [91, 95, 89, 94, 90],
    [60, 65, 58, 70, 62],
    [78, 84, 80, 76, 85]
])

In [4]:
print(marks.shape)

(5, 5)


In [5]:
print(marks.shape[0])

5


In [6]:
print(marks.shape[1])

5


In [7]:
print(marks.sum(axis=1))

[419 377 459 315 403]


In [8]:
print(marks.mean(axis=1))

[83.8 75.4 91.8 63.  80.6]


In [9]:
print(marks.mean(axis=0))

[77.2 80.6 77.6 80.6 78.6]


### Indexing and slicing

In [10]:
marks[0]

array([85, 78, 92, 88, 76])

In [11]:
marks[:, 0]

array([85, 72, 91, 60, 78])

In [12]:
marks[:, 2]

array([92, 69, 89, 58, 80])

In [13]:
marks[:3]

array([[85, 78, 92, 88, 76],
       [72, 81, 69, 75, 80],
       [91, 95, 89, 94, 90]])

In [14]:
marks[:, :3]

array([[85, 78, 92],
       [72, 81, 69],
       [91, 95, 89],
       [60, 65, 58],
       [78, 84, 80]])

### Boolean masking

In [15]:
python_marks = marks[:, 0]

In [16]:
print(python_marks > 80)

[ True False  True False False]


In [17]:
print(marks[python_marks > 80])

[[85 78 92 88 76]
 [91 95 89 94 90]]


### Statistics

In [18]:
np.mean(marks)

np.float64(78.92)

In [21]:
np.median(marks)
np.std(marks)

np.float64(10.491596637309309)

In [22]:
np.min(marks)
np.max(marks)

np.int64(95)

In [23]:
np.percentile(marks, 25)
np.percentile(marks, 50)
np.percentile(marks, 75)

np.float64(88.0)

In [24]:
np.mean(marks, axis=0)
np.std(marks, axis=0)
np.min(marks, axis=0)
np.max(marks, axis=0)

array([91, 95, 92, 94, 90])