In [1]:
import numpy as np

In [2]:
marks = np.array([
    [85, 78, 92, 88, 76],
    [72, 81, 69, 75, 80],
    [91, 95, 89, 94, 90],
    [60, 65, 58, 70, 62],
    [78, 84, 80, 76, 85]
])

In [3]:
print(marks.shape)

(5, 5)


In [4]:
print(marks.shape[0])

5


In [5]:
print(marks.shape[1])

5


In [6]:
print(marks.sum(axis=1))

[419 377 459 315 403]


In [7]:
print(marks.mean(axis=1))

[83.8 75.4 91.8 63.  80.6]


In [11]:
print(marks.mean(axis=0))

[77.2 80.6 77.6 80.6 78.6]


### Indexing and slicing

In [12]:
marks[0]

array([85, 78, 92, 88, 76])

In [13]:
marks[:, 0]

array([85, 72, 91, 60, 78])

In [14]:
marks[:, 2]

array([92, 69, 89, 58, 80])

In [15]:
marks[:3]

array([[85, 78, 92, 88, 76],
       [72, 81, 69, 75, 80],
       [91, 95, 89, 94, 90]])

In [16]:
marks[:, :3]

array([[85, 78, 92],
       [72, 81, 69],
       [91, 95, 89],
       [60, 65, 58],
       [78, 84, 80]])