In [1]:
import numpy as np

In [2]:
marks = np.array([
    [85, 78, 92, 88, 76],
    [72, 81, 69, 75, 80],
    [91, 95, 89, 94, 90],
    [60, 65, 58, 70, 62],
    [78, 84, 80, 76, 85]
])

In [3]:
print(marks.shape)

(5, 5)


In [4]:
print(marks.shape[0])

5


In [5]:
print(marks.shape[1])

5


In [6]:
print(marks.sum(axis=1))

[419 377 459 315 403]


In [7]:
print(marks.mean(axis=1))

[83.8 75.4 91.8 63.  80.6]


In [8]:
print(marks.mean(axis=0))

[77.2 80.6 77.6 80.6 78.6]


### Indexing and slicing

In [9]:
marks[0]

array([85, 78, 92, 88, 76])

In [10]:
marks[:, 0]

array([85, 72, 91, 60, 78])

In [11]:
marks[:, 2]

array([92, 69, 89, 58, 80])

In [12]:
marks[:3]

array([[85, 78, 92, 88, 76],
       [72, 81, 69, 75, 80],
       [91, 95, 89, 94, 90]])

In [13]:
marks[:, :3]

array([[85, 78, 92],
       [72, 81, 69],
       [91, 95, 89],
       [60, 65, 58],
       [78, 84, 80]])

### Boolean masking

In [14]:
python_marks = marks[:, 0]

In [15]:
print(python_marks > 80)

[ True False  True False False]


In [16]:
print(marks[python_marks > 80])

[[85 78 92 88 76]
 [91 95 89 94 90]]


### Statistics

In [17]:
np.mean(marks)

np.float64(78.92)

In [18]:
np.median(marks)
np.std(marks)

np.float64(10.491596637309309)

In [19]:
np.min(marks)
np.max(marks)

np.int64(95)

In [20]:
np.percentile(marks, 25)
np.percentile(marks, 50)
np.percentile(marks, 75)

np.float64(88.0)

In [21]:
np.mean(marks, axis=0)
np.std(marks, axis=0)
np.min(marks, axis=0)
np.max(marks, axis=0)

array([91, 95, 92, 94, 90])

### Ranking

In [22]:
averages = marks.mean(axis=1)

In [23]:
np.argsort(averages)

array([3, 1, 4, 0, 2])

### Random data generation

In [24]:
marks = np.random.randint(0, 101, size=(100, 5))

### Linear Algebra with NumPy

In [1]:
# Vectors

In [2]:
import numpy as np

In [3]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


In [4]:
np.dot(a, b)
np.linalg.norm(a)

np.float64(7.483314773547883)

In [6]:
# Matrices
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [10]:
A + B

array([[ 6,  8],
       [10, 12]])

In [11]:
A - B

array([[-4, -4],
       [-4, -4]])

In [8]:
A * B

array([[ 5, 12],
       [21, 32]])

In [9]:
A @ B

array([[19, 22],
       [43, 50]])

In [12]:
# Matrix operations
A.T
np.linalg.det(A)
np.linalg.inv(A)
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))